import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.scss'

const inter = Rubik({ 
  subsets: ['latin'], 
  style: ['normal','italic'],
  weight: ['400','300','500','700','800','900'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={inter.className}>{children}</body>
    </html>
  )
}
